# Generated by Django 5.1.6 on 2025-05-12 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_avatar_user_bio_user_name_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='/avatar/avatar.svg', null=True, upload_to='users/profile/'),
        ),
    ]
