# Generated by Django 5.1.6 on 2025-05-12 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_groups', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
    ]
