# Generated by Django 5.1.6 on 2025-05-14 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_groups', '0003_alter_message_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='body',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='message',
            name='media',
            field=models.FileField(default=1, upload_to='messages/'),
            preserve_default=False,
        ),
    ]
