# Generated by Django 5.1.6 on 2025-05-14 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_groups', '0004_alter_message_body_alter_message_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='messages/'),
        ),
    ]
